spring:
  datasource:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

jwt:
  key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ
  client-id: client # client id (for web or mobile app)
  secret: secret # secret for client
  resource-server-client-id: resourceserver # client id (for resource server)
  resource-server-secret: resourceserversecret # secret for resource server
